openapi: 3.0.3
info:
  title: Omega Momiji frontend API
  description: |-
    TODO: Fill me
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: SendMessage
    description: Sending messages
  - name: Chat
    description: Chat actions
  - name: InteractionActions
    description: Interaction actions
paths:
  /chats/{chat_id}/text-messages:
    post:
      tags:
        - SendMessage
      summary: Send a message
      description: Send a message to a corresponding messenger the frontend is implemented for
      operationId: sendMessage
      parameters:
        - name: chat_id
          in: path
          description: Chat id.
          required: true
          schema:
            type: string
            example: 1337
      requestBody:
        description: Message data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageResponse'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageClientErrorResponse'
        '500':
          description: Something bad happened on server side
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericServerErrorResponse'
  /chats/{chat_id}/admins:
    get:
      tags:
        - Chat
      summary: Get admins of a chat
      operationId: getAdmins
      parameters:
        - name: chat_id
          in: path
          description: Chat id.
          required: true
          schema:
            type: string
            example: 1337
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatAdminsResponse'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAdminsClientErrorResponse'
        '500':
          description: Something bad happened on server side
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericServerErrorResponse'
  /chats/{chat_id}/actions/typing:
    post:
      tags:
        - InteractionActions
      summary: Send typing action
      operationId: ActionTyping
      parameters:
        - name: chat_id
          in: path
          description: Chat id.
          required: true
          schema:
            type: string
            example: 1337
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionTypingClientErrorResponse'
        '500':
          description: Something bad happened on server side
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericServerErrorResponse'
    delete:
      tags:
        - InteractionActions
      summary: Interrupt typing action
      operationId: ActionTypingInterrupt
      parameters:
        - name: chat_id
          in: path
          description: Chat id.
          required: true
          schema:
            type: string
            example: 1337
      responses:
        '200':
          description: Successful operation
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterruptTypingClientErrorResponse'
        '500':
          description: Something bad happened on server side
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericServerErrorResponse'

components:
  schemas:
    # region send message
    SendMessageRequest:
      required:
        - text
      type: object
      properties:
        text:
          type: string
          example: Hello world!
        reply_to:
          type: string
          example: '10'
          description: A messenger native message ID
    SendMessageResponse:
      type: object
      properties:
        message_id:
          type: string
          example: '10'
          description: A messenger native message ID that was sent
    SendMessageClientErrorResponse:
      type: object
      properties:
        error_message:
          type: string
          example: 'Invalid ID was received'
          description: A messenger native message ID that was sent
        error_code:
          type: string
          example: INVALID_ID
          description: Message type
          enum:
            - INVALID_ID
            - OTHER
    # endregion send message
    # region actions typing
    ActionTypingClientErrorResponse:
      type: object
      properties:
        error_message:
          type: string
          example: 'Invalid chat ID was received'
        error_code:
          type: string
          example: INVALID_ID
          description: Message type
          enum:
            - INVALID_CHAT_ID
            - OTHER
    InterruptTypingClientErrorResponse:
      type: object
      properties:
        error_message:
          type: string
          example: 'Invalid chat ID was received'
        error_code:
          type: string
          example: INVALID_ID
          description: Message type
          enum:
            - INVALID_ID
            - OTHER
    # endregion actions typing
    # region /chats/{chat-id}/admins
    ChatAdminsResponse:
      type: object
      properties:
        admin_ids:
          type: array
          items:
            type: string
          example:
            - 12345
            - 54321
    GetAdminsClientErrorResponse:
      type: object
      properties:
        error_message:
          type: string
          example: 'Unable to get admin list: insufficient privileges'
        error_code:
          type: string
          example: INSUFFICIENT_PRIVILEGES
          description: Message type
          enum:
            - INSUFFICIENT_PRIVILEGES
            - OTHER
    # endregion /chats/{chat-id}/admins
    # region Other
    GenericServerErrorResponse:
      type: object
      properties:
        error_message:
          type: string
          example: 'Target messenger is not available for some reason'
          description: A messenger native message ID that was sent
        error_code:
          type: string
          example: NOT_AVAILABLE
          description: Message type
          enum:
            - NOT_AVAILABLE
            - OTHER
    # endregion
