openapi: 3.0.3
info:
  title: Omega Momiji messenger gateway
  description: |-
    A gateway that connects backend logic with various frontends.
  version: 1.0.0
servers:
  - url: http://localhost:8091
tags:
  - name: Inbox
    description: Everything about receiving a message
  - name: Outbox
    description: Everything about sending messages
paths:
  /inbox/text-messages:
    post:
      tags:
        - Inbox
      summary: Receive a text message
      description: >-
        Receive a message from frontend.
        This endpoint should be used by frontends.
        This is a PUT method because messages with same id, chat id and frontend can be updated
      operationId: receiveMessage
      requestBody:
        description: Message content
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxMessagesRequest'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Client did wrong
        '500':
          description: Server did wrong. You're on your own now
  /outbox/text-messages:
    post:
      tags:
        - Outbox
      summary: Send a text message
      description: Send a text message to a frontend. This endpoint should be used by bot logic
      operationId: sendTextMessage
      requestBody:
        description: Message to send
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendTextMessageRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendTextMessageResponse'
        '400':
          description: Client did wrong
        '500':
          description: Server did wrong. You're on your own now
  /frontends:
    get:
      tags:
        - Frontend
      summary: Get frontend names on this gateway
      description: Get registered frontend names on this gateway. Mostly for debug purposes
      operationId: frontendNames
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrontendNamesResponse'
  /frontends/{frontend}/messages/{chat-id}/{message-id}:
    get:
      tags:
        - Frontend
      summary: Get single message
      description: Get single message from frontend
      operationId: getSingleMessage
      parameters:
        - name: frontend
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: telegram
        - name: chat-id
          in: path
          description: Chat ID from frontend
          required: true
          schema:
            type: string
            example: '1337'
        - name: message-id
          in: path
          description: Message ID from chat and frontend
          required: true
          schema:
            type: string
            example: '1337'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: 'Target messenger is not available for some reason'
                    description: A messenger native message ID that was sent
                  error_code:
                    type: string
                    example: FRONTEND_NOT_FOUND
                    description: Message type
                    enum:
                      - FRONTEND_NOT_FOUND
                      - CHAT_NOT_FOUND
                      - MESSAGE_NOT_FOUND
        '500':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: 'Target messenger is not available for some reason'
                    description: A messenger native message ID that was sent
                  error_code:
                    type: string
                    example: OTHER
                    description: Message type
                    enum:
                      - OTHER
  /frontends/{frontend}/messages/{chat-id}:
    get:
      tags:
        - Frontend
      summary: Get pageable messages
      description: Get pageable messages from frontend
      operationId: getMessagePage
      parameters:
        - name: frontend
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: telegram
        - name: chat-id
          in: path
          description: Chat ID from frontend
          required: true
          schema:
            type: string
            example: '1337'
        - name: page
          in: query
          description: Page number
          required: true
          schema:
            type: integer
            example: 1
        - name: number
          in: query
          description: Page number
          required: true
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
  /frontends/{frontend}/chats/{chat-id}:
    get:
      tags:
        - Frontend
      summary: Get pageable messages
      description: Get pageable messages from frontend
      operationId: getChat
      parameters:
        - name: frontend
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: telegram
        - name: chat-id
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: '1337'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Frontend not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: 'Target messenger is not available for some reason'
                    description: A messenger native message ID that was sent
                  error_code:
                    type: string
                    example: FRONTEND_NOT_FOUND
                    description: Message type
                    enum:
                      - FRONTEND_NOT_FOUND
                      - CHAT_NOT_FOUND
  /frontends/{frontend}/users/{user-id}:
    get:
      tags:
        - Frontend
      summary: Get pageable messages
      description: Get pageable messages from frontend
      operationId: getUser
      parameters:
        - name: frontend
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: telegram
        - name: user-id
          in: path
          description: Frontend name
          required: true
          schema:
            type: string
            example: '1337'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Frontend not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    example: 'Target messenger is not available for some reason'
                    description: A messenger native message ID that was sent
                  error_code:
                    type: string
                    example: FRONTEND_NOT_FOUND
                    description: Message type
                    enum:
                      - FRONTEND_NOT_FOUND
                      - USER_NOT_FOUND
components:
  schemas:
    # region /inbox/text-messages
    InboxMessagesRequest:
      type: object
      required:
        - id
        - author
        - chat
        - frontend
        - type
      properties:
        from_user:
          $ref: '#/components/schemas/InboxUser'
        chat:
          $ref: '#/components/schemas/InboxChat'
        forward_from:
          $ref: '#/components/schemas/InboxUser'
        frontend:
          type: string
          description: Frontend name. Frontend should write here its name
          example: telegram
        text:
          type: string
          description: Message text
          example: Hello world!
        reply_to_message_id:
          type: integer
          example: 1337
    InboxUser:
      type: object
      properties:
        id:
          type: string
          example: '1337'
        first_name:
          type: string
          example: 'Firstname'
        last_name:
          type: string
          example: 'Lastname'
        username:
          type: string
          example: 'username'
        is_bot:
          type: boolean
          example: true
    InboxChat:
      type: object
      properties:
        id:
          type: string
          example: '1337'
        title:
          type: string
          example: 'Chat title'
        type:
          type: string
          example: PRIVATE
          enum:
            - PRIVATE
            - BOT
            - GROUP
            - SUPERGROUP
            - CHANNEL
        first_name:
          type: string
          example: 'Firstname'
        last_name:
          type: string
          example: 'Lastname'
        username:
          type: string
          example: 'username'
    # endregion /inbox/text-messages
    FrontendNamesResponse:
      type: object
      required:
        - names
      properties:
        names:
          type: array
          description: A list of frontend names. You can send messages to this frontends
          example:
            - telegram
            - discord
          items:
            type: string
    SendTextMessageRequest:
      type: object
      required:
        - frontend
        - text
        - chat_id
      properties:
        frontend:
          type: string
          description: Frontend name to which the message should be sent
          example: telegram
        text:
          type: string
          description: Message body
          example: Hello world!
        chat_id:
          type: string
          description: Native for frontend chat ID
          example: '123567'
        reply_to_message_id:
          type: string
          description: Native for frontend message ID to reply to
          example: '1'
    SendTextMessageResponse:
      type: object
      properties:
        error_message:
          type: string
          description: If you're licky, there will be a error message
          example: Something bad happened!
        message_id:
          type: string
          description: Native message ID
          example: '10'
    # region Other
    Message:
      type: object
      properties:
        id:
          type: integer
          example: 1337
        native_id:
          type: string
          example: '1337'
        from_user:
          $ref: '#/components/schemas/User'
        chat:
          $ref: '#/components/schemas/Chat'
        forward_from:
          $ref: '#/components/schemas/User'
        reply_to_message_id:
          type: integer
          example: 1337
        text:
          type: string
          example: Message string
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1337
        native_id:
          type: string
          example: '1337'
        first_name:
          type: string
          example: 'Firstname'
        last_name:
          type: string
          example: 'Lastname'
        username:
          type: string
          example: 'username'
        is_bot:
          type: boolean
          example: true
    Chat:
      type: object
      properties:
        id:
          type: integer
          example: 1337
        native_id:
          type: string
          example: '1337'
        title:
          type: string
          example: 'Chat title'
        type:
          type: string
          example: PRIVATE
          enum:
            - PRIVATE
            - BOT
            - GROUP
            - SUPERGROUP
            - CHANNEL
        first_name:
          type: string
          example: 'Firstname'
        last_name:
          type: string
          example: 'Lastname'
        username:
          type: string
          example: 'username'
    # endregion
